### ISSUE TITLE
Document and automate dev-setup

### ISSUE THREAD

**Issue by bkcsoft** [gitpods/gitpods#40]
dev-notes are quite scares, I had to figure out (by opening the db) that none of the tables or anything had been created (even though `gitpods dev setup` says that "it's now setup"). Then firing up a cockroachdb shell to create everything manually. Then off to `bcrypt-generator.com` to make the password-hash to create a test user. Not very developer-friendly :sweat_smile: 

Proposal:
- Have the DB be a bind-mount into `./dev/database` so it's persistant between restarts
- Have a `dev teardown` that wipes the database and all repos. (`rm -rf ./dev` essentially)
- Have `dev setup` run the db-migrations to create the necessary tables
- Have `dev setup` create a test-user `insert if not exists` sort-of

Extras:
- Have `dev setup` create generated data to do manual tests on (users, repos, etc...)

**Comment by metalmatze** [comment]
Thank you this is very good feedback I will surely address in the next days. :+1: 
I think we can do exactly what you written above.

As for creating a user: The API binary already has build-in support for creating these, as I used to `kubectl exec` into the container previously and the run the command to create a new user. On the local development environment you need to give it the database DSN.

Example command:
```
GITPODS_DATABASE_DSN='postgres://root@localhost:26257/gitpods?sslmode=disable' GITPODS_MIGRATIONS_PATH='./schema/postgres' ./dev/api users create --email metalmatze@example.com --username metalmatze --name 'Matthias Loibl' --password 'gitpods'
```
I never documented this anywhere so I didn't expect you to know. Sorry.
This command is probably deprecated anyway once we integrate Hydra and OIDC.

I fully agree that we should setup everything in `dev setup`. :100:
